#!groovy

// Generated by IBM TransformationAdvisor
// Tue Mar 26 13:32:43 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'pbwear'
    mvnCommands = '--version'
    test='false'
}