#!groovy

// Generated by IBM TransformationAdvisor
// Tue Mar 26 14:13:10 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'pbwear'
    mvnCommands = '--version'
    test='false'
}