#!groovy

// Generated by IBM TransformationAdvisor
// Tue Mar 26 09:46:49 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'pbwear'
    mvnCommands = '--version'
    test='false'
}